version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3333:3333"
    container_name: fast_double_backend
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: fast_double_frontend
    restart: always
    depends_on:
      backend:
        condition: service_healthy
